CREATE TABLE IF NOT EXISTS market_snapshots (
    id                      TEXT PRIMARY KEY,
    product_id              TEXT,
    candidate_id            TEXT,
    category                TEXT NOT NULL DEFAULT '',
    brand                   TEXT NOT NULL DEFAULT '',
    product_name            TEXT NOT NULL DEFAULT '',
    official_price_jpy      INTEGER,
    domestic_used_price_jpy INTEGER,
    domestic_buyback_price_jpy INTEGER,
    overseas_price_jpy      INTEGER,
    overseas_source         TEXT DEFAULT '',
    stock_status            TEXT DEFAULT '',
    sale_method             TEXT DEFAULT '',
    premium_gap_jpy         INTEGER,
    premium_gap_percent     REAL,
    overseas_gap_jpy        INTEGER,
    overseas_gap_percent    REAL,
    premium_score           REAL DEFAULT 0,
    scarcity_score          REAL DEFAULT 0,
    liquidity_score         REAL DEFAULT 0,
    overseas_gap_score      REAL DEFAULT 0,
    source_confidence       REAL DEFAULT 0,
    overall_score           REAL DEFAULT 0,
    captured_at             TEXT NOT NULL
)
