"""新UIの CSS（#new-ui-root の中だけに効く）。

色・文字・余白・角丸は design_tokens.py の変数だけを使う（直書きしない）。
横にはみ出さない決まり: グリッドの列は minmax(0,1fr)、長い文字は折り返す、
横に並べて収まらないもの（ジャンルの切り替え）はその要素の中だけで横スクロールする。
旧UIの .tab-wrap のような負のマージンは使わない。
"""

from __future__ import annotations

from src.content.ui import design_tokens as t

ROOT_ID = "new-ui-root"


def _tone_css() -> str:
    return "".join(
        f".nu-tone-{tone}{{--t-fg:var(--tone-{tone}-fg);--t-bg:var(--tone-{tone}-bg);"
        f"--t-bd:var(--tone-{tone}-bd);}}"
        for tone in t.TONES)


def css() -> str:
    m, d, w, nav = t.BP_MOBILE, t.BP_DESKTOP, t.BP_WIDE, t.BP_TOPNAV
    r = f"#{ROOT_ID}"
    return (
        # ── 表示の切り替え（旧UIは DOM を残したまま隠す） ──
        f"html:not(.ui-new) {r}{{display:none!important}}"
        f"html.ui-new body>*:not({r}){{display:none!important}}"
        f"html.ui-new body{{background:{t.BASE_COLORS['bg']};margin:0}}"
        f"{r}{{{t.css_variables()}"
        "font-family:-apple-system,BlinkMacSystemFont,'Hiragino Sans','Noto Sans JP',sans-serif;"
        "color:var(--color-text);background:var(--color-bg);font-size:var(--font-md);line-height:1.6;"
        "min-height:100vh;"
        "padding-bottom:calc(var(--bottom-nav-h) + env(safe-area-inset-bottom) + var(--space-4))}"
        f"{r} *,{r} *::before,{r} *::after{{box-sizing:border-box}}"
        f"{r} [hidden]{{display:none!important}}"
        f"{r} ul,{r} ol{{list-style:none;margin:0;padding:0}}"
        ".nu-icon{display:block;flex:none}"
        ".nu-sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}"
        + _tone_css() +
        # スキップリンク・フォーカス
        ".nu-skip{position:absolute;left:-9999px;top:0}"
        ".nu-skip:focus{left:var(--space-2);top:var(--space-2);z-index:50;background:var(--color-surface);"
        "padding:var(--space-2) var(--space-3);border-radius:var(--radius-sm)}"
        f"{r} a:focus-visible,{r} summary:focus-visible,{r} [tabindex]:focus-visible,{r} input:focus-visible"
        "{outline:3px solid var(--color-focus);outline-offset:2px}"
        # ── ヘッダー ──
        ".nu-header{position:sticky;top:0;z-index:20;background:var(--color-surface);"
        "border-bottom:1px solid var(--color-border)}"
        ".nu-header__inner{max-width:var(--max-width);margin:0 auto;display:flex;align-items:center;"
        "gap:var(--space-3);padding:0 var(--space-4);min-height:56px}"
        ".nu-brand{display:inline-flex;align-items:center;gap:var(--space-2);min-height:44px;min-width:0;"
        "text-decoration:none;color:var(--color-text);flex:none}"
        ".nu-brand__mark{display:inline-flex;align-items:center;justify-content:center;width:32px;height:32px;"
        "border-radius:var(--radius-sm);background:var(--color-primary);color:var(--color-primary-contrast)}"
        ".nu-brand__name{font-size:var(--font-md);font-weight:800;white-space:nowrap}"
        ".nu-brand__en{display:none;font-size:var(--font-xs);color:var(--color-subtle);font-weight:700;"
        "letter-spacing:.04em;white-space:nowrap}"
        ".nu-header__tools{margin-left:auto;display:flex;align-items:center;gap:var(--space-1);min-width:0}"
        ".nu-header__meta{font-size:var(--font-xs);color:var(--color-muted);white-space:nowrap;overflow:hidden;"
        "text-overflow:ellipsis;min-width:0;font-variant-numeric:tabular-nums}"
        ".nu-iconbtn{display:inline-flex;align-items:center;justify-content:center;width:44px;height:44px;"
        "flex:none;border-radius:var(--radius-sm);color:var(--color-muted);text-decoration:none}"
        ".nu-iconbtn:hover,.nu-iconbtn[aria-current=page]{color:var(--color-primary);background:var(--color-primary-soft)}"
        # 上部ナビ（768px 以上）
        ".nu-topnav{display:none}"
        ".nu-topnav__link{display:inline-flex;align-items:center;min-height:56px;padding:0 var(--space-3);"
        "color:var(--color-muted);text-decoration:none;font-size:var(--font-sm);font-weight:700;white-space:nowrap;"
        "border-bottom:2px solid transparent}"
        ".nu-topnav__link:hover{color:var(--color-text)}"
        ".nu-topnav__link[aria-current=page]{color:var(--color-primary);border-bottom-color:var(--color-primary)}"
        # ボトムナビ（768px 未満）
        ".nu-bottomnav{position:fixed;left:0;right:0;bottom:0;z-index:30;display:grid;"
        "grid-template-columns:repeat(5,minmax(0,1fr));background:var(--color-surface);"
        "border-top:1px solid var(--color-border);padding-bottom:env(safe-area-inset-bottom)}"
        ".nu-bottomnav__link{display:flex;flex-direction:column;align-items:center;justify-content:center;"
        "gap:2px;min-height:var(--bottom-nav-h);min-width:44px;font-size:var(--font-xs);font-weight:700;"
        "color:var(--color-subtle);text-decoration:none}"
        ".nu-bottomnav__link[aria-current=page]{color:var(--color-primary)}"
        f"@media (min-width:{nav}px){{.nu-topnav{{display:flex}}.nu-bottomnav{{display:none}}"
        f"{r}{{padding-bottom:0}}}}"
        f"@media (min-width:{w}px){{.nu-brand__en{{display:inline}}}}"
        # 「情報確認」の文字は、幅が足りないとき（360px 未満と、上部ナビと並ぶ 640〜1023px）は省いて時刻だけ出す
        f"@media (max-width:359px),(min-width:{nav}px) and (max-width:{w - 1}px){{.nu-header__metalabel{{display:none}}}}"
        # ── 本文 ──
        ".nu-main{max-width:var(--max-width);margin:0 auto;padding:var(--space-4)}"
        f"@media (min-width:{d}px){{.nu-main{{padding:var(--space-5) var(--space-5) var(--space-6)}}}}"
        ".nu-main:focus{outline:none}"
        ".nu-home__title{font-size:var(--font-lg);font-weight:800;line-height:1.35;margin:0 0 var(--space-1)}"
        f"@media (min-width:{d}px){{.nu-home__title{{font-size:var(--font-xl)}}}}"
        ".nu-h2{font-size:var(--font-md);font-weight:800;margin:var(--space-5) 0 var(--space-3);line-height:1.4}"
        ".nu-h2row{display:flex;flex-wrap:wrap;align-items:baseline;gap:var(--space-2) var(--space-3);"
        "margin:var(--space-5) 0 var(--space-3)}"
        ".nu-h2row .nu-h2{margin:0}"
        ".nu-ctx{margin:0;font-size:var(--font-sm);color:var(--color-muted)}"
        ".nu-ctx [data-nu-catlabel]{font-weight:800;color:var(--color-primary)}"
        ".nu-ctx__clear{margin-left:var(--space-2);display:inline-flex;align-items:center;min-height:44px;"
        "color:var(--color-primary)}"
        ".nu-lead{font-size:var(--font-sm);color:var(--color-muted);margin:var(--space-1) 0 0}"
        # ジャンル（モバイル2列・640px 以上3列・1024px 以上6列）
        ".nu-cats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-3)}"
        f"@media (min-width:{m}px){{.nu-cats{{grid-template-columns:repeat(3,minmax(0,1fr))}}}}"
        f"@media (min-width:{w}px){{.nu-cats{{grid-template-columns:repeat(6,minmax(0,1fr))}}}}"
        # モバイルは横並び（アイコン | 名前・件数）で低く、640px 以上は縦のカード
        ".nu-cat{display:grid;grid-template-columns:auto minmax(0,1fr);grid-template-rows:auto auto;"
        "column-gap:var(--space-3);align-items:center;min-height:68px;"
        "padding:var(--space-3);background:var(--color-surface);border:1px solid var(--color-border);"
        "border-radius:var(--radius-md);text-decoration:none;color:var(--color-text);min-width:0;"
        "transition:border-color .15s,background-color .15s}"
        ".nu-cat__icon{grid-row:1/3}"
        ".nu-cat__label{align-self:end}.nu-cat__count{align-self:start}"
        f"@media (min-width:{m}px){{.nu-cat{{display:flex;flex-direction:column;align-items:flex-start;"
        "gap:var(--space-2);min-height:112px;padding:var(--space-4)}"
        ".nu-cat__label,.nu-cat__count{align-self:auto}}"
        ".nu-cat:hover{border-color:var(--color-primary)}"
        ".nu-cat[aria-current=true]{border-color:var(--color-primary);background:var(--color-primary-soft);"
        "box-shadow:inset 0 0 0 1px var(--color-primary)}"
        ".nu-cat__icon,.nu-purpose__icon,.nu-pagehead__icon{display:inline-flex;align-items:center;"
        "justify-content:center;width:40px;height:40px;flex:none;border-radius:var(--radius-sm);"
        "background:var(--color-primary-soft);color:var(--color-primary)}"
        ".nu-cat__label{font-size:var(--font-md);font-weight:800;line-height:1.3}"
        ".nu-cat__count{font-size:var(--font-sm);color:var(--color-muted);font-variant-numeric:tabular-nums}"
        # 0件は消さずに控えめに（押せば空状態のページが開く）
        "[data-zero] .nu-cat__count,.nu-purpose__count[data-zero]{color:var(--color-subtle);font-weight:400}"
        # 目的（モバイル1列の行・640px 以上2列・1024px 以上4列）
        ".nu-purposes{display:grid;grid-template-columns:minmax(0,1fr);gap:var(--space-2)}"
        f"@media (min-width:{m}px){{.nu-purposes{{grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-3)}}}}"
        f"@media (min-width:{w}px){{.nu-purposes{{grid-template-columns:repeat(4,minmax(0,1fr))}}"
        ".nu-purposes--list{grid-template-columns:repeat(2,minmax(0,1fr))}}"
        ".nu-purpose{display:flex;align-items:center;gap:var(--space-3);min-height:72px;height:100%;"
        "padding:var(--space-3) var(--space-4);background:var(--color-surface);border:1px solid var(--color-border);"
        "border-radius:var(--radius-md);text-decoration:none;color:var(--color-text);min-width:0;"
        "transition:border-color .15s}"
        ".nu-purpose:hover{border-color:var(--color-primary)}"
        ".nu-purpose__body{display:flex;flex-direction:column;min-width:0;flex:1}"
        ".nu-purpose__label{font-size:var(--font-md);font-weight:800;line-height:1.35}"
        ".nu-purpose__desc{font-size:var(--font-xs);color:var(--color-muted);line-height:1.45;overflow-wrap:anywhere}"
        ".nu-purpose__count{flex:none;font-size:var(--font-md);font-weight:800;font-variant-numeric:tabular-nums;"
        "color:var(--color-text)}"
        ".nu-purpose__chev{flex:none;color:var(--color-subtle)}"
        # 補助リンク（小さく）
        ".nu-quicks{display:flex;flex-wrap:wrap;gap:var(--space-2);margin:var(--space-5) 0 0}"
        ".nu-quick{display:inline-flex;align-items:center;gap:var(--space-1);min-height:44px;"
        "padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-sm);"
        "background:var(--color-surface);font-size:var(--font-sm);font-weight:700;text-decoration:none;"
        "color:var(--color-text)}"
        "a.nu-quick:hover{border-color:var(--color-primary);color:var(--color-primary)}"
        ".nu-quick--soon{color:var(--color-subtle);background:var(--tone-neutral-bg);cursor:not-allowed}"
        ".nu-quick__tag{margin-left:var(--space-1);padding:0 6px;border-radius:var(--radius-sm);font-size:var(--font-xs);"
        "font-weight:700;color:var(--color-muted);background:var(--tone-neutral-bg);border:1px solid var(--color-border)}"
        # ── 目的のページ ──
        ".nu-crumbs ol{display:flex;flex-wrap:wrap;align-items:center;gap:var(--space-1);font-size:var(--font-xs);"
        "color:var(--color-muted)}"
        ".nu-crumbs li+li::before{content:'/';margin-right:var(--space-1);color:var(--color-subtle)}"
        ".nu-crumbs a{display:inline-flex;align-items:center;min-height:44px;color:var(--color-primary)}"
        ".nu-pagehead{display:flex;align-items:center;gap:var(--space-3);margin:0 0 var(--space-3)}"
        # 関連する目的への1行（利益商品 ⇔ せどりルートの違いを示す）
        ".nu-related{margin:0 0 var(--space-3);font-size:var(--font-sm);color:var(--color-muted)}"
        ".nu-related a{display:inline-flex;align-items:center;min-height:44px;color:var(--color-primary);font-weight:700}"
        ".nu-topnote{display:flex;flex-wrap:wrap;align-items:center;gap:var(--space-2);margin:0 0 var(--space-3);"
        "padding:var(--space-2) var(--space-3);border-radius:var(--radius-sm);background:var(--color-primary-soft);"
        "font-size:var(--font-sm)}"
        ".nu-topnote a{display:inline-flex;align-items:center;min-height:44px;color:var(--color-primary);font-weight:700}"
        ".nu-page__title{font-size:var(--font-lg);font-weight:800;margin:0;line-height:1.3}"
        f"@media (min-width:{d}px){{.nu-page__title{{font-size:var(--font-xl)}}}}"
        # ジャンルの切り替え（収まらない幅では、この中だけで横スクロール）
        ".nu-chips{display:flex;gap:var(--space-2);overflow-x:auto;padding:2px;"
        "margin:0 0 var(--space-3);scrollbar-width:none}"
        ".nu-chips::-webkit-scrollbar{display:none}"
        ".nu-chip{display:inline-flex;align-items:center;flex:none;min-height:44px;padding:0 var(--space-4);"
        "border:1px solid var(--color-border);border-radius:var(--radius-sm);background:var(--color-surface);"
        "font-size:var(--font-sm);font-weight:700;text-decoration:none;color:var(--color-muted);white-space:nowrap}"
        ".nu-chip:hover{border-color:var(--color-primary);color:var(--color-text)}"
        ".nu-chip[aria-current=true]{background:var(--color-primary);border-color:var(--color-primary);"
        "color:var(--color-primary-contrast)}"
        # 絞り込みの枠
        ".nu-filter{display:flex;flex-wrap:wrap;align-items:center;gap:var(--space-2) var(--space-3);"
        "padding:var(--space-2) 0 var(--space-3);border-bottom:1px solid var(--color-border);margin-bottom:var(--space-4)}"
        ".nu-filter__search{display:flex;align-items:center;gap:var(--space-2);flex:1 1 220px;min-width:0;"
        "min-height:44px;padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-sm);"
        "background:var(--tone-neutral-bg);color:var(--color-subtle)}"
        ".nu-filter__search--wide{max-width:560px;margin:var(--space-3) 0}"
        ".nu-filter__search input{border:0;background:transparent;font:inherit;font-size:var(--font-sm);"
        "min-width:0;width:100%;color:var(--color-muted)}"
        ".nu-filter__sort{display:inline-flex;align-items:center;font-size:var(--font-sm);color:var(--color-muted)}"
        ".nu-filter__count{margin-left:auto;font-size:var(--font-sm);font-weight:800;font-variant-numeric:tabular-nums}"
        # 一覧（カード）
        ".nu-list{display:grid;grid-template-columns:minmax(0,1fr);gap:var(--space-3)}"
        f"@media (min-width:{d}px){{.nu-list{{grid-template-columns:repeat(2,minmax(0,1fr))}}}}"
        f"@media (min-width:{w}px){{.nu-list{{grid-template-columns:repeat(3,minmax(0,1fr))}}}}"
        ".nu-list>li{min-width:0;display:flex}.nu-list>li>.nu-card{flex:1}"
        ".nu-card{display:flex;flex-direction:column;gap:var(--space-2);min-width:0;padding:var(--space-4);"
        "background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-md)}"
        ".nu-card__head{display:flex;align-items:flex-start;justify-content:space-between;gap:var(--space-2)}"
        ".nu-card__title{font-size:var(--font-md);font-weight:700;margin:0;line-height:1.4;overflow-wrap:anywhere}"
        ".nu-card__sub{margin:0;font-size:var(--font-sm);color:var(--color-muted);overflow-wrap:anywhere}"
        ".nu-card__metric{margin:0;font-size:var(--font-lg);font-weight:800;font-variant-numeric:tabular-nums}"
        ".nu-card__meta{margin:0;font-size:var(--font-sm);font-variant-numeric:tabular-nums}"
        ".nu-cd{display:block;font-size:var(--font-xs);color:var(--color-muted);font-variant-numeric:tabular-nums}"
        # 状態バッジ（文字で伝える。絵文字は出さず、色の点を添える）
        ".nu-badge{flex:none;display:inline-flex;align-items:center;gap:6px;padding:2px var(--space-2);"
        "border-radius:var(--radius-sm);font-size:var(--font-xs);font-weight:700;line-height:1.5;"
        "color:var(--t-fg);background:var(--t-bg);border:1px solid var(--t-bd);white-space:nowrap}"
        ".nu-badge>span[aria-hidden]{display:none}"
        ".nu-badge::before{content:'';width:6px;height:6px;border-radius:50%;background:currentColor;flex:none}"
        # ボタン（高さ44px以上）
        ".nu-btn{display:flex;align-items:center;justify-content:center;width:100%;min-height:44px;"
        "padding:0 var(--space-4);border-radius:var(--radius-sm);font-size:var(--font-sm);font-weight:700;"
        "text-align:center;text-decoration:none;line-height:1.3;margin-top:auto}"
        ".nu-btn--primary{background:var(--color-primary);color:var(--color-primary-contrast)}"
        ".nu-btn--secondary{background:var(--color-surface);color:var(--color-primary);border:1px solid var(--color-border)}"
        ".nu-btn--link{width:auto;justify-content:flex-start;padding:0;color:var(--color-primary);text-decoration:underline}"
        # 開閉
        ".nu-details summary{display:flex;align-items:center;min-height:44px;cursor:pointer;"
        "font-size:var(--font-sm);font-weight:700;color:var(--color-primary)}"
        ".nu-details dl{display:grid;grid-template-columns:auto minmax(0,1fr);gap:var(--space-1) var(--space-3);"
        "margin:0;font-size:var(--font-sm)}"
        ".nu-details dt{color:var(--color-muted)}.nu-details dd{margin:0;overflow-wrap:anywhere}"
        # 空状態・注意
        ".nu-empty{padding:var(--space-6) var(--space-4);text-align:center;background:var(--color-surface);"
        "border:1px dashed var(--color-border);border-radius:var(--radius-md)}"
        ".nu-empty__msg{margin:0;font-size:var(--font-md);font-weight:700}"
        ".nu-empty__hint{margin:var(--space-1) 0 0;font-size:var(--font-sm);color:var(--color-muted)}"
        ".nu-notice{margin:var(--space-3) 0 0;padding:var(--space-2) var(--space-3);border-radius:var(--radius-sm);"
        "background:var(--tone-warning-bg);color:var(--tone-warning-fg);font-size:var(--font-sm)}"
        ".nu-rule{margin:var(--space-4) 0 0;font-size:var(--font-xs);color:var(--color-subtle)}"
        ".nu-disclaimer{margin:var(--space-5) 0 0;font-size:var(--font-xs);color:var(--color-subtle)}"
        ".nu-lead--home{margin:0 0 var(--space-2)}"
        # フッター（全ページ共通・1回だけ）
        ".nu-footer{border-top:1px solid var(--color-border);background:var(--color-surface);margin-top:var(--space-6)}"
        ".nu-footer__inner{max-width:var(--max-width);margin:0 auto;padding:var(--space-4);display:flex;flex-wrap:wrap;"
        "align-items:center;gap:var(--space-2) var(--space-4);font-size:var(--font-xs);color:var(--color-subtle)}"
        ".nu-footer__brand{font-weight:800;color:var(--color-muted)}"
        ".nu-footer a{display:inline-flex;align-items:center;min-height:44px;color:var(--color-muted)}"
        ".nu-footer__note{flex-basis:100%;margin:0}"
        ".nu-linklist{display:grid;gap:var(--space-2)}"
        # 開発用の照合表（?debug=1 のときだけ表示。表は横スクロールの枠の中だけ）
        ".nu-debug{margin-top:var(--space-5);padding:var(--space-3);border:1px solid var(--color-border);"
        "border-radius:var(--radius-md);background:var(--color-surface);font-size:var(--font-xs)}"
        ".nu-debug__scroll{overflow-x:auto}.nu-debug table{border-collapse:collapse}"
        ".nu-debug th,.nu-debug td{border:1px solid var(--color-border);padding:var(--space-1) var(--space-2);text-align:left}"
        ".nu-debug tr[data-match='0'] td{background:var(--tone-warning-bg)}"
    )
