"""新UIの CSS（#new-ui-root の中だけに効く）。

色・文字・余白・角丸は design_tokens.py の変数だけを使う（直書きしない）。
横にはみ出さない決まり: グリッドの列は minmax(0,1fr)、長い文字は折り返す、
横に並べて収まらないもの（ジャンルの切り替え）はその要素の中だけで横スクロールする。
旧UIの .tab-wrap のような負のマージンは使わない。
"""

from __future__ import annotations

from src.content.ui import design_tokens as t

ROOT_ID = "new-ui-root"


def _tone_css() -> str:
    return "".join(
        f".nu-tone-{tone}{{--t-fg:var(--tone-{tone}-fg);--t-bg:var(--tone-{tone}-bg);"
        f"--t-bd:var(--tone-{tone}-bd);}}"
        for tone in t.TONES)


def css() -> str:
    m, d, w, nav = t.BP_MOBILE, t.BP_DESKTOP, t.BP_WIDE, t.BP_TOPNAV
    r = f"#{ROOT_ID}"
    return (
        # ── 表示の切り替え（旧UIは DOM を残したまま隠す） ──
        f"html:not(.ui-new) {r}{{display:none!important}}"
        f"html.ui-new body>*:not({r}){{display:none!important}}"
        f"html.ui-new body{{background:{t.BASE_COLORS['bg']};margin:0}}"
        f"{r}{{{t.css_variables()}"
        "font-family:-apple-system,BlinkMacSystemFont,'Hiragino Sans','Noto Sans JP',sans-serif;"
        "color:var(--color-text);background:var(--color-bg);font-size:var(--font-md);line-height:1.6;"
        "min-height:100vh;"
        "padding-bottom:calc(var(--bottom-nav-h) + env(safe-area-inset-bottom) + var(--space-4))}"
        f"{r} *,{r} *::before,{r} *::after{{box-sizing:border-box}}"
        f"{r} [hidden]{{display:none!important}}"
        f"{r} ul,{r} ol{{list-style:none;margin:0;padding:0}}"
        ".nu-icon{display:block;flex:none}"
        ".nu-sr{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0);white-space:nowrap}"
        + _tone_css() +
        # スキップリンク・フォーカス
        ".nu-skip{position:absolute;left:-9999px;top:0}"
        ".nu-skip:focus{left:var(--space-2);top:var(--space-2);z-index:50;background:var(--color-surface);"
        "padding:var(--space-2) var(--space-3);border-radius:var(--radius-sm)}"
        f"{r} a:focus-visible,{r} summary:focus-visible,{r} [tabindex]:focus-visible,{r} input:focus-visible"
        "{outline:3px solid var(--color-focus);outline-offset:2px}"
        # ── ヘッダー ──
        ".nu-header{position:sticky;top:0;z-index:20;background:var(--color-surface);"
        "border-bottom:1px solid var(--color-border)}"
        ".nu-header__inner{max-width:var(--max-width);margin:0 auto;display:flex;align-items:center;"
        "gap:var(--space-3);padding:0 var(--space-4);min-height:56px}"
        ".nu-brand{display:inline-flex;align-items:center;gap:var(--space-2);min-height:44px;min-width:0;"
        "text-decoration:none;color:var(--color-text);flex:none}"
        ".nu-brand__mark{display:inline-flex;align-items:center;justify-content:center;width:32px;height:32px;"
        "border-radius:var(--radius-sm);background:var(--color-primary);color:var(--color-primary-contrast)}"
        ".nu-brand__name{font-size:var(--font-md);font-weight:800;white-space:nowrap}"
        ".nu-brand__en{display:none;font-size:var(--font-xs);color:var(--color-subtle);font-weight:700;"
        "letter-spacing:.04em;white-space:nowrap}"
        ".nu-header__tools{margin-left:auto;display:flex;align-items:center;gap:var(--space-1);min-width:0}"
        ".nu-header__meta{font-size:var(--font-xs);color:var(--color-muted);white-space:nowrap;overflow:hidden;"
        "text-overflow:ellipsis;min-width:0;font-variant-numeric:tabular-nums}"
        ".nu-iconbtn{display:inline-flex;align-items:center;justify-content:center;width:44px;height:44px;"
        "flex:none;border-radius:var(--radius-sm);color:var(--color-muted);text-decoration:none}"
        ".nu-iconbtn:hover,.nu-iconbtn[aria-current=page]{color:var(--color-primary);background:var(--color-primary-soft)}"
        # 上部ナビ（768px 以上）
        ".nu-topnav{display:none}"
        ".nu-topnav__link{display:inline-flex;align-items:center;min-height:56px;padding:0 var(--space-3);"
        "color:var(--color-muted);text-decoration:none;font-size:var(--font-sm);font-weight:700;white-space:nowrap;"
        "border-bottom:2px solid transparent}"
        ".nu-topnav__link:hover{color:var(--color-text)}"
        ".nu-topnav__link[aria-current=page]{color:var(--color-primary);border-bottom-color:var(--color-primary)}"
        # ボトムナビ（768px 未満）
        ".nu-bottomnav{position:fixed;left:0;right:0;bottom:0;z-index:30;display:grid;"
        "grid-template-columns:repeat(5,minmax(0,1fr));background:var(--color-surface);"
        "border-top:1px solid var(--color-border);padding-bottom:env(safe-area-inset-bottom)}"
        ".nu-bottomnav__link{display:flex;flex-direction:column;align-items:center;justify-content:center;"
        "gap:2px;min-height:var(--bottom-nav-h);min-width:44px;font-size:var(--font-xs);font-weight:700;"
        "color:var(--color-subtle);text-decoration:none}"
        ".nu-bottomnav__link[aria-current=page]{color:var(--color-primary)}"
        f"@media (min-width:{nav}px){{.nu-topnav{{display:flex}}.nu-bottomnav{{display:none}}"
        f"{r}{{padding-bottom:0}}}}"
        f"@media (min-width:{w}px){{.nu-brand__en{{display:inline}}}}"
        # 「情報確認」の文字は、幅が足りないとき（360px 未満と、上部ナビと並ぶ 640〜1023px）は省いて時刻だけ出す
        f"@media (max-width:359px),(min-width:{nav}px) and (max-width:{w - 1}px){{.nu-header__metalabel{{display:none}}}}"
        # ── 本文 ──
        ".nu-main{max-width:var(--max-width);margin:0 auto;padding:var(--space-4)}"
        f"@media (min-width:{d}px){{.nu-main{{padding:var(--space-5) var(--space-5) var(--space-6)}}}}"
        ".nu-main:focus{outline:none}"
        ".nu-home__title{font-size:var(--font-lg);font-weight:800;line-height:1.35;margin:0 0 var(--space-1)}"
        f"@media (min-width:{d}px){{.nu-home__title{{font-size:var(--font-xl)}}}}"
        ".nu-h2{font-size:var(--font-md);font-weight:800;margin:var(--space-5) 0 var(--space-3);line-height:1.4}"
        ".nu-h2row{display:flex;flex-wrap:wrap;align-items:baseline;gap:var(--space-2) var(--space-3);"
        "margin:var(--space-5) 0 var(--space-3)}"
        ".nu-h2row .nu-h2{margin:0}"
        ".nu-ctx{margin:0;font-size:var(--font-sm);color:var(--color-muted)}"
        ".nu-ctx [data-nu-catlabel]{font-weight:800;color:var(--color-primary)}"
        ".nu-ctx__clear{margin-left:var(--space-2);display:inline-flex;align-items:center;min-height:44px;"
        "color:var(--color-primary)}"
        ".nu-lead{font-size:var(--font-sm);color:var(--color-muted);margin:var(--space-1) 0 0}"
        # ジャンル（モバイル2列・640px 以上3列・1024px 以上6列）
        ".nu-cats{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-3)}"
        f"@media (min-width:{m}px){{.nu-cats{{grid-template-columns:repeat(3,minmax(0,1fr))}}}}"
        f"@media (min-width:{w}px){{.nu-cats{{grid-template-columns:repeat(6,minmax(0,1fr))}}}}"
        # モバイルは横並び（アイコン | 名前・件数）で低く、640px 以上は縦のカード
        ".nu-cat{display:grid;grid-template-columns:auto minmax(0,1fr);grid-template-rows:auto auto;"
        "column-gap:var(--space-3);align-items:center;min-height:68px;"
        "padding:var(--space-3);background:var(--color-surface);border:1px solid var(--color-border);"
        "border-radius:var(--radius-md);text-decoration:none;color:var(--color-text);min-width:0;"
        "transition:border-color .15s,background-color .15s}"
        ".nu-cat__icon{grid-row:1/3}"
        ".nu-cat__label{align-self:end}.nu-cat__count{align-self:start}"
        f"@media (min-width:{m}px){{.nu-cat{{display:flex;flex-direction:column;align-items:flex-start;"
        "gap:var(--space-2);min-height:112px;padding:var(--space-4)}"
        ".nu-cat__label,.nu-cat__count{align-self:auto}}"
        ".nu-cat:hover{border-color:var(--color-primary)}"
        ".nu-cat[aria-current=true]{border-color:var(--color-primary);background:var(--color-primary-soft);"
        "box-shadow:inset 0 0 0 1px var(--color-primary)}"
        ".nu-cat__icon,.nu-purpose__icon,.nu-pagehead__icon{display:inline-flex;align-items:center;"
        "justify-content:center;width:40px;height:40px;flex:none;border-radius:var(--radius-sm);"
        "background:var(--color-primary-soft);color:var(--color-primary)}"
        ".nu-cat__label{font-size:var(--font-md);font-weight:800;line-height:1.3}"
        ".nu-cat__count{font-size:var(--font-sm);color:var(--color-muted);font-variant-numeric:tabular-nums}"
        # 0件は消さずに控えめに（押せば空状態のページが開く）
        "[data-zero] .nu-cat__count,.nu-purpose__count[data-zero]{color:var(--color-subtle);font-weight:400}"
        # 目的（モバイル1列の行・640px 以上2列・1024px 以上4列）
        ".nu-purposes{display:grid;grid-template-columns:minmax(0,1fr);gap:var(--space-2)}"
        f"@media (min-width:{m}px){{.nu-purposes{{grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-3)}}}}"
        f"@media (min-width:{w}px){{.nu-purposes{{grid-template-columns:repeat(4,minmax(0,1fr))}}"
        ".nu-purposes--list{grid-template-columns:repeat(2,minmax(0,1fr))}}"
        ".nu-purpose{display:flex;align-items:center;gap:var(--space-3);min-height:72px;height:100%;"
        "padding:var(--space-3) var(--space-4);background:var(--color-surface);border:1px solid var(--color-border);"
        "border-radius:var(--radius-md);text-decoration:none;color:var(--color-text);min-width:0;"
        "transition:border-color .15s}"
        ".nu-purpose:hover{border-color:var(--color-primary)}"
        ".nu-purpose__body{display:flex;flex-direction:column;min-width:0;flex:1}"
        ".nu-purpose__label{font-size:var(--font-md);font-weight:800;line-height:1.35}"
        ".nu-purpose__desc{font-size:var(--font-xs);color:var(--color-muted);line-height:1.45;overflow-wrap:anywhere}"
        ".nu-purpose__count{flex:none;font-size:var(--font-md);font-weight:800;font-variant-numeric:tabular-nums;"
        "color:var(--color-text)}"
        ".nu-purpose__chev{flex:none;color:var(--color-subtle)}"
        # 補助リンク（小さく）
        ".nu-quicks{display:flex;flex-wrap:wrap;gap:var(--space-2);margin:var(--space-5) 0 0}"
        ".nu-quick{display:inline-flex;align-items:center;gap:var(--space-1);min-height:44px;"
        "padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-sm);"
        "background:var(--color-surface);font-size:var(--font-sm);font-weight:700;text-decoration:none;"
        "color:var(--color-text)}"
        "a.nu-quick:hover{border-color:var(--color-primary);color:var(--color-primary)}"
        ".nu-quick--soon{color:var(--color-subtle);background:var(--tone-neutral-bg);cursor:not-allowed}"
        ".nu-quick__tag{margin-left:var(--space-1);padding:0 6px;border-radius:var(--radius-sm);font-size:var(--font-xs);"
        "font-weight:700;color:var(--color-muted);background:var(--tone-neutral-bg);border:1px solid var(--color-border)}"
        # ── 目的のページ ──
        ".nu-crumbs ol{display:flex;flex-wrap:wrap;align-items:center;gap:var(--space-1);font-size:var(--font-xs);"
        "color:var(--color-muted)}"
        ".nu-crumbs li+li::before{content:'/';margin-right:var(--space-1);color:var(--color-subtle)}"
        ".nu-crumbs a{display:inline-flex;align-items:center;min-height:44px;color:var(--color-primary)}"
        ".nu-pagehead{display:flex;align-items:center;gap:var(--space-3);margin:0 0 var(--space-3)}"
        # 関連する目的への1行（利益商品 ⇔ せどりルートの違いを示す）
        ".nu-related{margin:0 0 var(--space-3);font-size:var(--font-sm);color:var(--color-muted)}"
        ".nu-related a{display:inline-flex;align-items:center;min-height:44px;color:var(--color-primary);font-weight:700}"
        ".nu-topnote{display:flex;flex-wrap:wrap;align-items:center;gap:var(--space-2);margin:0 0 var(--space-3);"
        "padding:var(--space-2) var(--space-3);border-radius:var(--radius-sm);background:var(--color-primary-soft);"
        "font-size:var(--font-sm)}"
        ".nu-topnote a{display:inline-flex;align-items:center;min-height:44px;color:var(--color-primary);font-weight:700}"
        ".nu-page__title{font-size:var(--font-lg);font-weight:800;margin:0;line-height:1.3}"
        f"@media (min-width:{d}px){{.nu-page__title{{font-size:var(--font-xl)}}}}"
        # ジャンルの切り替え（収まらない幅では、この中だけで横スクロール）
        ".nu-chips{display:flex;gap:var(--space-2);overflow-x:auto;padding:2px;"
        "margin:0 0 var(--space-3);scrollbar-width:none}"
        ".nu-chips::-webkit-scrollbar{display:none}"
        ".nu-chip{display:inline-flex;align-items:center;flex:none;min-height:44px;padding:0 var(--space-4);"
        "border:1px solid var(--color-border);border-radius:var(--radius-sm);background:var(--color-surface);"
        "font-size:var(--font-sm);font-weight:700;text-decoration:none;color:var(--color-muted);white-space:nowrap}"
        ".nu-chip:hover{border-color:var(--color-primary);color:var(--color-text)}"
        ".nu-chip[aria-current=true]{background:var(--color-primary);border-color:var(--color-primary);"
        "color:var(--color-primary-contrast)}"
        # 絞り込みの枠
        ".nu-filter{display:flex;flex-wrap:wrap;align-items:center;gap:var(--space-2) var(--space-3);"
        "padding:var(--space-2) 0 var(--space-3);border-bottom:1px solid var(--color-border);margin-bottom:var(--space-4)}"
        ".nu-filter__search{display:flex;align-items:center;gap:var(--space-2);flex:1 1 220px;min-width:0;"
        "min-height:44px;padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-sm);"
        "background:var(--tone-neutral-bg);color:var(--color-subtle)}"
        ".nu-filter__search--wide{max-width:560px;margin:var(--space-3) 0}"
        ".nu-filter__search input{border:0;background:transparent;font:inherit;font-size:var(--font-sm);"
        "min-width:0;width:100%;color:var(--color-muted)}"
        ".nu-filter__sort{display:inline-flex;align-items:center;font-size:var(--font-sm);color:var(--color-muted)}"
        ".nu-filter__count{margin-left:auto;font-size:var(--font-sm);font-weight:800;font-variant-numeric:tabular-nums}"
        # 一覧（カード）
        ".nu-list{display:grid;grid-template-columns:minmax(0,1fr);gap:var(--space-3)}"
        f"@media (min-width:{d}px){{.nu-list{{grid-template-columns:repeat(2,minmax(0,1fr))}}}}"
        f"@media (min-width:{w}px){{.nu-list{{grid-template-columns:repeat(3,minmax(0,1fr))}}}}"
        ".nu-list>li{min-width:0;display:flex}.nu-list>li>.nu-card{flex:1}"
        ".nu-card{display:flex;flex-direction:column;gap:var(--space-2);min-width:0;padding:var(--space-4);"
        "background:var(--color-surface);border:1px solid var(--color-border);border-radius:var(--radius-md)}"
        ".nu-card__head{display:flex;align-items:flex-start;justify-content:space-between;gap:var(--space-2)}"
        ".nu-card__title{font-size:var(--font-md);font-weight:700;margin:0;line-height:1.4;overflow-wrap:anywhere}"
        ".nu-card__sub{margin:0;font-size:var(--font-sm);color:var(--color-muted);overflow-wrap:anywhere}"
        ".nu-card__metric{margin:0;font-size:var(--font-lg);font-weight:800;font-variant-numeric:tabular-nums}"
        ".nu-card__meta{margin:0;font-size:var(--font-sm);font-variant-numeric:tabular-nums}"
        ".nu-cd{display:block;font-size:var(--font-xs);color:var(--color-muted);font-variant-numeric:tabular-nums}"
        # 状態バッジ（文字で伝える。絵文字は出さず、色の点を添える）
        ".nu-badge{flex:none;display:inline-flex;align-items:center;gap:6px;padding:2px var(--space-2);"
        "border-radius:var(--radius-sm);font-size:var(--font-xs);font-weight:700;line-height:1.5;"
        "color:var(--t-fg);background:var(--t-bg);border:1px solid var(--t-bd);white-space:nowrap}"
        ".nu-badge>span[aria-hidden]{display:none}"
        ".nu-badge::before{content:'';width:6px;height:6px;border-radius:50%;background:currentColor;flex:none}"
        # ボタン（高さ44px以上）
        ".nu-btn{display:flex;align-items:center;justify-content:center;width:100%;min-height:44px;"
        "padding:0 var(--space-4);border-radius:var(--radius-sm);font-size:var(--font-sm);font-weight:700;"
        "text-align:center;text-decoration:none;line-height:1.3;margin-top:auto}"
        ".nu-btn--primary{background:var(--color-primary);color:var(--color-primary-contrast)}"
        ".nu-btn--secondary{background:var(--color-surface);color:var(--color-primary);border:1px solid var(--color-border)}"
        ".nu-btn--link{width:auto;justify-content:flex-start;padding:0;color:var(--color-primary);text-decoration:underline}"
        # 開閉
        ".nu-details summary{display:flex;align-items:center;min-height:44px;cursor:pointer;"
        "font-size:var(--font-sm);font-weight:700;color:var(--color-primary)}"
        ".nu-details dl{display:grid;grid-template-columns:auto minmax(0,1fr);gap:var(--space-1) var(--space-3);"
        "margin:0;font-size:var(--font-sm)}"
        ".nu-details dt{color:var(--color-muted)}.nu-details dd{margin:0;overflow-wrap:anywhere}"
        # 空状態・注意
        ".nu-empty{padding:var(--space-6) var(--space-4);text-align:center;background:var(--color-surface);"
        "border:1px dashed var(--color-border);border-radius:var(--radius-md)}"
        ".nu-empty__msg{margin:0;font-size:var(--font-md);font-weight:700}"
        ".nu-empty__hint{margin:var(--space-1) 0 0;font-size:var(--font-sm);color:var(--color-muted)}"
        ".nu-notice{margin:var(--space-3) 0 0;padding:var(--space-2) var(--space-3);border-radius:var(--radius-sm);"
        "background:var(--tone-warning-bg);color:var(--tone-warning-fg);font-size:var(--font-sm)}"
        ".nu-rule{margin:var(--space-4) 0 0;font-size:var(--font-xs);color:var(--color-subtle)}"
        ".nu-disclaimer{margin:var(--space-5) 0 0;font-size:var(--font-xs);color:var(--color-subtle)}"
        ".nu-lead--home{margin:0 0 var(--space-2)}"
        # フッター（全ページ共通・1回だけ）
        ".nu-footer{border-top:1px solid var(--color-border);background:var(--color-surface);margin-top:var(--space-6)}"
        ".nu-footer__inner{max-width:var(--max-width);margin:0 auto;padding:var(--space-4);display:flex;flex-wrap:wrap;"
        "align-items:center;gap:var(--space-2) var(--space-4);font-size:var(--font-xs);color:var(--color-subtle)}"
        ".nu-footer__brand{font-weight:800;color:var(--color-muted)}"
        ".nu-footer a{display:inline-flex;align-items:center;min-height:44px;color:var(--color-muted)}"
        ".nu-footer__note{flex-basis:100%;margin:0}"
        ".nu-linklist{display:grid;gap:var(--space-2)}"
        # ── 利益商品（UI Phase 2）: 1200px 以上は比較テーブル、未満はカード（テーブルを横スクロールさせない） ──
        ".nu-otools{display:grid;gap:var(--space-2);margin:0 0 var(--space-3)}"
        ".nu-otools__row{display:flex;flex-wrap:wrap;align-items:center;gap:var(--space-2)}"
        ".nu-otools__lbl{font-size:var(--font-xs);font-weight:700;color:var(--color-subtle);min-width:4em}"
        ".nu-segs{display:inline-flex;flex-wrap:wrap;border:1px solid var(--color-border);border-radius:var(--radius-sm);"
        "overflow:hidden;background:var(--color-surface)}"
        ".nu-seg{display:inline-flex;align-items:center;min-height:44px;padding:0 var(--space-3);font-size:var(--font-sm);"
        "font-weight:700;color:var(--color-muted);text-decoration:none;border-right:1px solid var(--color-border)}"
        ".nu-seg:last-child{border-right:0}"
        ".nu-seg:hover{color:var(--color-text);background:var(--color-primary-soft)}"
        ".nu-seg[aria-current=true]{background:var(--color-primary);color:var(--color-primary-contrast)}"
        ".nu-ofilters{display:flex;flex-wrap:wrap;gap:var(--space-2)}"
        # モバイル: 並び替えは1行（行の中だけ横に送る。ページ全体は横スクロールしない）
        f"@media (max-width:{m - 1}px){{.nu-otools__lbl{{display:none}}"
        ".nu-otools__row{flex-wrap:nowrap;min-width:0;overflow-x:auto;scrollbar-width:none}"
        ".nu-otools__row>*{flex:0 0 auto}.nu-ofilters{flex-wrap:nowrap}"
        # 「商品を絞り込む」は行の先頭に出す（横に送らなくても見える）
        "[data-nu-search-toggle]{order:-1}"
        ".nu-segs{flex-wrap:nowrap;max-width:none}"
        ".nu-seg{flex:0 0 auto;white-space:nowrap;padding:0 var(--space-2)}}}"
        ".nu-chip--sm{padding:0 var(--space-3);gap:var(--space-1);font:inherit;font-size:var(--font-sm);font-weight:700;"
        "cursor:pointer}"
        "button.nu-chip{background:var(--color-surface)}"
        ".nu-chip--soon{color:var(--color-subtle);background:var(--tone-neutral-bg);cursor:not-allowed}"
        ".nu-osearch{max-width:480px}"
        ".nu-filter__search--live{background:var(--color-surface);color:var(--color-text)}"
        ".nu-filter__search--live input{color:var(--color-text);outline:none}"
        ".nu-filter__search--live:focus-within{border-color:var(--color-primary);box-shadow:0 0 0 2px var(--color-primary-soft)}"
        ".nu-oresult{margin:0;font-size:var(--font-sm);font-weight:700;color:var(--color-muted);font-variant-numeric:tabular-nums}"
        # テーブル（1200px 以上）
        ".nu-otable-wrap{display:none}"
        ".nu-otable{width:100%;border-collapse:separate;border-spacing:0;background:var(--color-surface);"
        "border:1px solid var(--color-border);border-radius:var(--radius-md);font-size:var(--font-sm)}"
        ".nu-otable th,.nu-otable td{padding:var(--space-2);text-align:left;vertical-align:middle;"
        "border-bottom:1px solid var(--color-border)}"
        ".nu-otable thead th{position:sticky;top:56px;z-index:2;background:var(--tone-neutral-bg);font-size:var(--font-xs);"
        "font-weight:700;color:var(--color-muted);white-space:nowrap}"
        ".nu-otable thead th:first-child{border-top-left-radius:var(--radius-md)}"
        ".nu-otable thead th:last-child{border-top-right-radius:var(--radius-md)}"
        ".nu-otable tbody tr:last-child>*{border-bottom:0}"
        ".nu-orow:hover>*{background:var(--color-bg)}"
        ".nu-otable .nu-num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}"
        ".nu-oname{display:block;font-size:var(--font-sm);font-weight:800;color:var(--color-text);overflow-wrap:anywhere}"
        ".nu-omodel,.nu-osub{display:block;font-size:var(--font-xs);font-weight:400;color:var(--color-subtle)}"
        ".nu-ocol-name{min-width:150px}.nu-ocol-cat{white-space:nowrap;color:var(--color-muted)}"
        # 店名は途中で折り返さない（「公式スト／ア」のように切れない幅）
        ".nu-ocol-src{min-width:9.5em;word-break:keep-all;overflow-wrap:anywhere}"
        # 1200px 未満ではジャンルの列を省く（上のジャンルの切り替えで分かる）。買う・売る場所は折り返す

        ".nu-ocol-time{white-space:nowrap;color:var(--color-muted);font-size:var(--font-xs)}"
        ".nu-profit{color:var(--color-success);font-weight:800}"
        ".nu-otable .nu-profit{font-size:var(--font-md)}"
        ".nu-otable .nu-profit .nu-osub{font-size:var(--font-xs);font-weight:400}"
        ".nu-roi{font-weight:700;font-variant-numeric:tabular-nums}"
        ".nu-rowbtn{display:inline-flex;align-items:center;justify-content:center;min-height:44px;min-width:44px;"
        "padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-sm);"
        "background:var(--color-surface);color:var(--color-primary);font:inherit;font-size:var(--font-sm);"
        "font-weight:700;cursor:pointer;white-space:nowrap}"
        ".nu-rowbtn[aria-expanded=true]{background:var(--color-primary-soft);border-color:var(--color-primary)}"
        f"{r} button:focus-visible{{outline:3px solid var(--color-focus);outline-offset:2px}}"
        ".nu-odetail-row>td{background:var(--color-bg)}"
        ".nu-odetail__grid{display:grid;grid-template-columns:minmax(0,1fr);gap:var(--space-4)}"
        f"@media (min-width:{d}px){{.nu-odetail__grid{{grid-template-columns:repeat(2,minmax(0,1fr))}}}}"
        ".nu-odetail__h{margin:0 0 var(--space-2);font-size:var(--font-xs);font-weight:800;color:var(--color-muted)}"
        ".nu-break{display:grid;gap:2px;font-size:var(--font-sm)}"
        ".nu-break li{display:flex;justify-content:space-between;gap:var(--space-3)}"
        ".nu-break li>span{color:var(--color-muted)}"
        ".nu-break b{font-weight:700;font-variant-numeric:tabular-nums;text-align:right}"
        ".nu-break__total{border-top:1px solid var(--color-border);padding-top:var(--space-1);margin-top:var(--space-1)}"
        ".nu-break__total b{color:var(--color-success)}"
        ".nu-break__note{font-size:var(--font-xs);color:var(--color-subtle)}"
        ".nu-break--sub{margin-top:var(--space-2)}"
        ".nu-odetail__links{display:flex;flex-wrap:wrap;gap:var(--space-2);margin-top:var(--space-3)}"
        ".nu-odetail__links .nu-btn{width:auto}"
        # カード（1200px 未満。640px 以上は2列。1枚を低く、短いスクロールで比べられる密度）
        ".nu-ocards{display:grid;gap:var(--space-2)}"
        ".nu-ocard{padding:var(--space-3);background:var(--color-surface);border:1px solid var(--color-border);"
        "border-radius:var(--radius-md);min-width:0}"
        ".nu-ocard__head{display:flex;align-items:flex-start;justify-content:space-between;gap:var(--space-2)}"
        ".nu-ocard__title{margin:0;font-size:var(--font-md);font-weight:800;line-height:1.35;overflow-wrap:anywhere}"
        ".nu-ocard__route{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-2);margin:var(--space-2) 0}"
        ".nu-ocard__route>div{padding:var(--space-2);background:var(--color-bg);border-radius:var(--radius-sm);min-width:0}"
        ".nu-ocard__route dt{font-size:var(--font-xs);font-weight:700;color:var(--color-subtle)}"
        ".nu-ocard__route dd{margin:0}"
        ".nu-ocard__shop{display:block;font-size:var(--font-sm);font-weight:700;overflow-wrap:anywhere}"
        ".nu-ocard__price{display:block;font-size:var(--font-md);font-weight:800;font-variant-numeric:tabular-nums}"
        ".nu-ocard__result{display:flex;align-items:flex-end;gap:var(--space-5)}"
        ".nu-ocard__btn{margin-left:auto}"
        ".nu-ocard__time{display:block;font-size:var(--font-xs);color:var(--color-subtle)}"
        ".nu-ocard__lbl{display:block;font-size:var(--font-xs);color:var(--color-subtle)}"
        ".nu-ocard__profit{font-size:var(--font-xl);font-variant-numeric:tabular-nums;line-height:1.2}"
        ".nu-ocard__roi{font-size:var(--font-lg);line-height:1.2}"
        ".nu-ocard .nu-odetail{margin-top:var(--space-3);padding-top:var(--space-3);border-top:1px solid var(--color-border)}"
        f"@media (min-width:{m}px){{.nu-ocards{{grid-template-columns:repeat(2,minmax(0,1fr));align-items:start}}}}"
        f"@media (min-width:{t.BP_OPP_TABLE}px){{.nu-otable-wrap{{display:block}}.nu-ocards{{display:none}}}}"
        "[data-nu-opp-hide-empty][hidden]{display:none!important}"
        ".nu-empty__cta{margin-top:var(--space-3)}"
        f"@media (min-width:{m}px){{.nu-empty__cta{{display:inline-flex;width:auto}}}}"
        # ── 抽選・予約（UI Phase 3）: 1件1要素。モバイルはカード、1024px 以上は比較しやすい行 ──
        ".nu-llist{display:grid;gap:var(--space-2)}"
        ".nu-lrow{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:var(--space-2) var(--space-3);"
        "grid-template-areas:'st st' 'main main' 'price profit' 'when when' 'cta cta' 'det det';"
        "padding:var(--space-3);background:var(--color-surface);border:1px solid var(--color-border);"
        "border-radius:var(--radius-md);min-width:0}"
        ".nu-lrow[hidden],.nu-lhead[hidden]{display:none!important}"
        ".nu-lrow__status{grid-area:st;display:flex;align-items:center;justify-content:space-between;gap:var(--space-2);"
        "flex-wrap:wrap;min-width:0}"
        ".nu-lrow__status .nu-cd{display:inline;font-size:var(--font-sm);font-weight:800;color:var(--color-text)}"
        ".nu-lrow__main{grid-area:main;min-width:0}"
        ".nu-lrow__title{margin:0;font-size:var(--font-md);font-weight:800;line-height:1.35;overflow-wrap:anywhere}"
        ".nu-lrow__shop{margin:2px 0 0;font-size:var(--font-sm);font-weight:700;color:var(--color-muted);overflow-wrap:anywhere}"
        ".nu-lrow__cat{font-weight:400}"
        ".nu-lrow__chips{display:flex;flex-wrap:wrap;gap:var(--space-1);margin:var(--space-1) 0 0}"
        ".nu-lchip{display:inline-flex;align-items:center;padding:1px var(--space-2);border-radius:999px;"
        "font-size:var(--font-xs);font-weight:700;background:var(--tone-neutral-bg);color:var(--color-muted)}"
        ".nu-lchip--warn{background:var(--tone-warning-bg);color:var(--tone-warning-fg)}"
        ".nu-lrow__price{grid-area:price;min-width:0}.nu-lrow__profit{grid-area:profit;min-width:0}"
        ".nu-lrow__price,.nu-lrow__profit{padding:var(--space-1) var(--space-2);background:var(--color-bg);border-radius:var(--radius-sm)}"
        ".nu-lrow__lbl{display:block;font-size:var(--font-xs);font-weight:700;color:var(--color-subtle)}"
        ".nu-lrow__val{display:block;font-size:var(--font-md);font-weight:800;font-variant-numeric:tabular-nums}"
        ".nu-lrow__val--muted{font-size:var(--font-sm);color:var(--color-muted)}"
        ".nu-lrow__ref{display:block;font-size:var(--font-xs);color:var(--color-subtle);font-variant-numeric:tabular-nums}"
        # モバイルは締切と確認時刻を1行に（PC は縦に並べる）
        ".nu-lrow__when{grid-area:when;display:flex;flex-wrap:wrap;align-items:baseline;gap:2px var(--space-2);min-width:0}"
        ".nu-lrow__when .nu-when{font-size:var(--font-sm);font-weight:700;font-variant-numeric:tabular-nums}"
        ".nu-lrow__upd{font-size:var(--font-xs);color:var(--color-subtle)}"
        ".nu-lrow__sub{font-size:var(--font-xs);font-weight:700;color:var(--color-muted)}"
        # 在庫再開: 長い状態（「在庫未確認（更新待ち）」）は折り返す。最終確認は読みやすい濃さ
        ".nu-lrow__status .nu-badge{white-space:normal;max-width:100%}"
        ".nu-rrow .nu-lrow__upd{font-size:var(--font-sm);font-weight:700;color:var(--color-muted)}"
        ".nu-rmsg{margin:var(--space-1) 0 0;font-size:var(--font-xs);font-weight:700;color:var(--tone-warning-fg)}"
        "[data-nu-rs-hide-empty][hidden]{display:none!important}"
        # せどりルート（UI Phase 5）: 買う・売るの店名、出品価格の参考（確定ルートと見た目でも分ける）
        ".nu-lrow__shopname{display:block;font-size:var(--font-sm);font-weight:700;overflow-wrap:anywhere}"
        "[data-nu-rt-hide-empty][hidden]{display:none!important}"
        ".nu-refs{margin-top:var(--space-6);padding:var(--space-3);border:1px dashed var(--color-border);"
        "border-radius:var(--radius-md);background:var(--tone-neutral-bg)}"
        ".nu-refs__title{margin:0;font-size:var(--font-md);font-weight:800;display:flex;align-items:center;gap:var(--space-2)}"
        ".nu-refs__tag{font-size:var(--font-xs);font-weight:700;padding:1px var(--space-2);border-radius:999px;"
        "background:var(--tone-warning-bg);color:var(--tone-warning-fg)}"
        ".nu-refs__note{margin:var(--space-1) 0 var(--space-2);font-size:var(--font-sm);color:var(--color-muted)}"
        ".nu-refs__list{display:grid;gap:var(--space-1);list-style:none;margin:0;padding:0}"
        # モバイルは1列（商品名・価格・確認時刻・リンクを縦に）。1024px 以上で4列
        ".nu-refrow{display:grid;grid-template-columns:minmax(0,1fr);gap:var(--space-1) var(--space-3);align-items:center;"
        "padding:var(--space-2);background:var(--color-surface);border-radius:var(--radius-sm);min-width:0}"
        ".nu-refrow[hidden]{display:none}"
        ".nu-refrow__main{min-width:0}.nu-refrow__name{display:block;font-weight:700;overflow-wrap:anywhere}"
        ".nu-refrow__market{font-size:var(--font-xs);color:var(--color-muted)}"
        ".nu-refrow__val{display:block;font-weight:800;font-variant-numeric:tabular-nums}"
        ".nu-refrow__time{grid-column:1/-1;display:flex;flex-wrap:wrap;gap:var(--space-2);align-items:center;"
        "font-size:var(--font-xs);color:var(--color-subtle)}"
        ".nu-refrow__btn{grid-column:1/-1;width:100%;min-height:44px}"
        f"@media (min-width:{w}px){{.nu-refrow{{grid-template-columns:minmax(0,1fr) 12rem 10rem 9.5rem}}"
        ".nu-refrow__time{grid-column:auto}.nu-refrow__btn{grid-column:auto}"
        # ルートの行は買う・売るの欄を広く（根拠を読めるように）
        ".nu-lrow.nu-route,.nu-page[data-nu-page=routes] .nu-lhead{grid-template-columns:10rem minmax(0,1fr) 12rem 13rem 9.5rem 9.5rem}"
        ".nu-route .nu-lrow__status .nu-badge{white-space:nowrap}}"
        ".nu-lrow__cta{grid-area:cta;min-width:0}.nu-lrow__cta:empty{display:none}"
        ".nu-lrow__cta .nu-btn{width:100%;min-height:44px;margin:0}"
        ".nu-ldetail{grid-area:det;min-width:0;border-top:1px solid var(--color-border);padding-top:var(--space-1)}"
        ".nu-ldetail summary{display:flex;align-items:center;min-height:44px;cursor:pointer;"
        "font-size:var(--font-sm);font-weight:700;color:var(--color-primary)}"
        ".nu-ldetail__dl{display:grid;grid-template-columns:auto minmax(0,1fr);gap:var(--space-1) var(--space-3);"
        "margin:0 0 var(--space-2);font-size:var(--font-sm)}"
        ".nu-ldetail__dl dt{color:var(--color-muted);white-space:nowrap}"
        ".nu-ldetail__dl dd{margin:0;overflow-wrap:anywhere;white-space:pre-line}"
        ".nu-lrow__src{width:auto;min-height:44px}"
        ".nu-lhead{display:none}"
        f"@media (min-width:{w}px){{"
        ".nu-lrow,.nu-lhead{grid-template-columns:8.5rem minmax(0,1fr) 7.5rem 9rem 12.5rem 9.5rem;"
        "grid-template-areas:'st main price profit when cta' 'det det det det det det';align-items:center}"
        ".nu-lrow__status{flex-direction:column;align-items:flex-start;justify-content:center}"
        ".nu-lrow__when{flex-direction:column;align-items:flex-start}"
        ".nu-lrow__price,.nu-lrow__profit{padding:0;background:none}"
        ".nu-lrow__price .nu-lrow__lbl,.nu-lrow__profit>.nu-lrow__lbl{position:absolute;width:1px;height:1px;overflow:hidden;"
        "clip:rect(0 0 0 0);white-space:nowrap}"
        ".nu-lhead{display:grid;gap:var(--space-2) var(--space-3);padding:0 var(--space-3);font-size:var(--font-xs);"
        "font-weight:700;color:var(--color-subtle)}"
        ".nu-lrow{padding:var(--space-2) var(--space-3)}"
        ".nu-ldetail{border-top:1px dashed var(--color-border);padding-top:0}"
        # PC はマウス操作なので詳細の行を低くする（モバイルは 44px のまま）
        ".nu-ldetail summary{min-height:32px}"
        "}"
        # ページ切り替え
        ".nu-pager{display:flex;flex-wrap:wrap;justify-content:center;gap:var(--space-1);margin:var(--space-4) 0 0}"
        ".nu-pager__link{display:inline-flex;align-items:center;justify-content:center;min-width:44px;min-height:44px;"
        "padding:0 var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-sm);"
        "background:var(--color-surface);color:var(--color-text);text-decoration:none;font-weight:700;"
        "font-variant-numeric:tabular-nums}"
        ".nu-pager__link[aria-current=page]{background:var(--color-primary);border-color:var(--color-primary);"
        "color:var(--color-primary-contrast)}"
        # 開発用の照合表（?debug=1 のときだけ表示。表は横スクロールの枠の中だけ）
        ".nu-debug{margin-top:var(--space-5);padding:var(--space-3);border:1px solid var(--color-border);"
        "border-radius:var(--radius-md);background:var(--color-surface);font-size:var(--font-xs)}"
        ".nu-debug__scroll{overflow-x:auto}.nu-debug table{border-collapse:collapse}"
        ".nu-debug th,.nu-debug td{border:1px solid var(--color-border);padding:var(--space-1) var(--space-2);text-align:left}"
        ".nu-debug tr[data-match='0'] td{background:var(--tone-warning-bg)}"
        + _product_css(m, d, w)
    )


def _product_css(m: int, d: int, w: int) -> str:
    """商品詳細（UI Phase 6）と商品の検索。トークンだけを使う（影・グラデーションは使わない）。"""
    return (
        # 一覧からのリンク
        ".nu-pdlink{display:inline-flex;align-items:center;min-height:44px;padding:0 var(--space-3);"
        "color:var(--color-primary);font-weight:700;font-size:var(--font-sm);text-decoration:underline;"
        "text-underline-offset:3px}"
        ".nu-pdlink:focus-visible,.nu-pd-tab:focus-visible,.nu-pd-back:focus-visible{outline:3px solid var(--color-focus);"
        "outline-offset:2px}"
        # ページ
        ".nu-pd-back{display:inline-flex;align-items:center;min-height:44px;color:var(--color-primary);"
        "font-weight:700;text-decoration:none}"
        ".nu-pd{display:grid;gap:var(--space-3);min-width:0}"
        ".nu-pd-head{display:grid;gap:var(--space-1);min-width:0}"
        ".nu-pd-title{margin:0;font-size:var(--font-xl);line-height:1.3;overflow-wrap:anywhere}"
        ".nu-pd-meta{margin:0;color:var(--color-muted);font-size:var(--font-sm);overflow-wrap:anywhere}"
        ".nu-pd-state{margin:0;display:flex;flex-wrap:wrap;align-items:center;gap:var(--space-1) var(--space-3)}"
        ".nu-pd-state .nu-osub{display:inline}"
        # 主要な数値（モバイルは2列、PC は5列）
        ".nu-pd-summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:var(--space-2);margin:0}"
        ".nu-pd-metric{min-width:0;padding:var(--space-2) var(--space-3);border:1px solid var(--color-border);"
        "border-radius:var(--radius-md);background:var(--color-surface)}"
        ".nu-pd-metric dt{font-size:var(--font-xs);color:var(--color-muted)}"
        ".nu-pd-metric dd{margin:0;min-width:0}"
        ".nu-pd-val{display:block;font-size:var(--font-lg);font-weight:800;font-variant-numeric:tabular-nums;"
        "overflow-wrap:anywhere}"
        ".nu-pd-metric--profit{border-color:var(--tone-success-bd);background:var(--tone-success-bg)}"
        ".nu-pd-metric--profit .nu-pd-val{color:var(--color-success)}"
        ".nu-pd-metric .nu-osub{overflow-wrap:anywhere}"
        # 想定純利益はモバイルでは1段目に全幅（いちばん知りたい値を最初に）
        ".nu-pd-metric--main,.nu-pd-metric--wide{grid-column:1/-1}"
        f"@media (min-width:{d}px){{.nu-pd-summary{{grid-template-columns:repeat(5,minmax(0,1fr))}}"
        ".nu-pd-metric--main,.nu-pd-metric--wide{grid-column:auto}}"
        ".nu-pd-jump{display:inline-flex;align-items:center;min-height:44px;color:var(--color-primary);"
        "font-weight:700;font-size:var(--font-sm)}"
        ".nu-pd-headcta{margin:var(--space-1) 0 0}.nu-pd-headcta .nu-btn{width:auto}"
        ".nu-pd-profit{scroll-margin-top:72px}.nu-pd-profit:focus{outline:3px solid var(--color-focus);outline-offset:2px}"
        ".nu-pd-assume{display:inline-block;margin-right:var(--space-1);padding:0 4px;border:1px solid var(--color-border);"
        "border-radius:var(--radius-sm);font-size:var(--font-xs);color:var(--color-muted)}"
        ".nu-break li>span .nu-osub{display:block}.nu-pd-profit .nu-break li>b{white-space:nowrap}"
        ".nu-pd-morerows{margin-top:var(--space-2)}"
        ".nu-pd-morerows>summary{min-height:44px;display:flex;align-items:center;cursor:pointer;"
        "color:var(--color-primary);font-weight:700;font-size:var(--font-sm)}"
        # タブ
        ".nu-pd-tabs{display:flex;gap:var(--space-1);border-bottom:1px solid var(--color-border);overflow-x:auto;"
        "scrollbar-width:none}"
        ".nu-pd-tab{flex:0 0 auto;min-height:44px;padding:0 var(--space-3);border:0;border-bottom:3px solid transparent;"
        "background:none;color:var(--color-muted);font:inherit;font-weight:700;cursor:pointer}"
        ".nu-pd-tab[aria-selected=true]{color:var(--color-primary);border-bottom-color:var(--color-primary)}"
        ".nu-pd-panel{display:grid;gap:var(--space-3);min-width:0}"
        ".nu-pd-box{min-width:0;padding:var(--space-3);border:1px solid var(--color-border);border-radius:var(--radius-md);"
        "background:var(--color-surface)}"
        ".nu-pd-h{margin:0 0 var(--space-2);font-size:var(--font-md)}"
        ".nu-pd-empty,.nu-pd-none{margin:0;color:var(--color-muted)}"
        ".nu-pd-why,.nu-pd-reflist{margin:var(--space-1) 0 0;padding-left:1.2em;font-size:var(--font-sm)}"
        ".nu-pd-reflist li{margin:2px 0}.nu-pd-reflist b{font-variant-numeric:tabular-nums;margin:0 var(--space-1)}"
        ".nu-pd-more{display:inline-flex;align-items:center;min-height:44px;color:var(--color-primary);font-weight:700}"
        # 比較の表（1024px 未満は1行ずつのカード。横スクロールさせない）
        ".nu-pd-table{width:100%;border-collapse:collapse;font-size:var(--font-sm)}"
        ".nu-pd-table th,.nu-pd-table td{padding:var(--space-2);border-bottom:1px solid var(--color-border);"
        "text-align:left;vertical-align:top;min-width:0;overflow-wrap:anywhere}"
        ".nu-pd-table thead th{font-size:var(--font-xs);color:var(--color-muted);font-weight:700}"
        ".nu-pd-table .nu-num{text-align:right;font-variant-numeric:tabular-nums;white-space:nowrap}"
        ".nu-pd-best{background:var(--color-primary-soft)}"
        ".nu-pd-bestmark{display:inline-block;margin-left:var(--space-1);font-size:var(--font-xs);font-weight:700;"
        "color:var(--color-primary)}"
        ".nu-pd-acq{font-weight:800}"
        ".nu-pd-q{font-size:var(--font-xs)}"
        ".nu-pd-ctacell .nu-btn{width:auto;white-space:nowrap}"
        ".nu-btn--sm{min-height:44px;padding:0 var(--space-3);font-size:var(--font-sm)}"
        # 8列の表は 1024px 未満では収まらないので、1行ずつのカードにする
        f"@media (max-width:{w - 1}px){{"
        ".nu-pd-table thead{position:absolute;width:1px;height:1px;overflow:hidden;clip:rect(0 0 0 0)}"
        ".nu-pd-table,.nu-pd-table tbody,.nu-pd-table tr,.nu-pd-table th,.nu-pd-table td{display:block;width:auto}"
        ".nu-pd-table tr{padding:var(--space-2) 0;border-bottom:1px solid var(--color-border)}"
        ".nu-pd-table th,.nu-pd-table td{border:0;padding:2px 0}"
        ".nu-pd-table td[data-label]:not([data-label=''])::before{content:attr(data-label);display:inline-block;"
        "min-width:6.5em;margin-right:var(--space-2);color:var(--color-muted);font-size:var(--font-xs)}"
        ".nu-pd-table .nu-num{text-align:left;white-space:normal}"
        ".nu-pd-table td .nu-osub{display:inline;margin-left:var(--space-1)}"
        ".nu-pd-ctacell .nu-btn{width:100%;margin-top:var(--space-1)}"
        ".nu-pd-table th{font-size:var(--font-md)}}"
        # 抽選・予約（runtime が状態・日時・ボタンを書き換える）
        ".nu-pd-lot{display:grid;grid-template-columns:auto minmax(0,1fr);gap:var(--space-1) var(--space-2);"
        "align-items:center;padding:var(--space-2) 0;border-bottom:1px solid var(--color-border)}"
        ".nu-pd-lot__main{min-width:0;overflow-wrap:anywhere}"
        ".nu-pd-lot__cta{grid-column:1/-1}.nu-pd-lot__cta .nu-btn{width:auto}"
        ".nu-pd-lot .nu-pd-lotdet{grid-area:auto;grid-column:1/-1}.nu-pd-lotdet .nu-btn{width:auto;margin-top:var(--space-1)}"
        # 価格の履歴（SVG。種別ごとに線の形を変える。色だけで区別しない）
        ".nu-pd-chart{margin:0}.nu-pd-chart>svg{display:block;width:100%;height:auto;max-height:240px}"
        ".nu-pd-legend svg{flex:0 0 28px;width:28px;height:8px}"
        ".nu-hs{stroke-width:2;fill:none;stroke:var(--color-primary)}circle.nu-hs{fill:var(--color-surface)}"
        ".nu-hs--buyback{stroke:var(--color-success)}.nu-hs--listing{stroke:var(--color-muted)}"
        ".nu-hs--sold_median{stroke:var(--color-warning)}"
        # 軸の文字の大きさは SVG の単位（図は幅 640 の座標を画面の幅に合わせて縮める。高さの上限で PC はおよそ1.1倍）。
        # 狭い画面ほど大きい値にして、表示はどの幅でもおよそ 12〜15px にする
        ".nu-pd-chart{--nu-hs-fs:24px}.nu-hs-ax{fill:var(--color-muted);font-size:var(--nu-hs-fs)}"
        "@media (min-width:480px){.nu-pd-chart{--nu-hs-fs:18px}}@media (min-width:640px){.nu-pd-chart{--nu-hs-fs:13px}}"
        ".nu-hs-base{stroke:var(--color-border)}"
        ".nu-hs-grid{stroke:var(--color-border);stroke-dasharray:4 4}"
        ".nu-pd-legend{display:flex;flex-wrap:wrap;gap:var(--space-1) var(--space-3);margin:var(--space-2) 0 0;"
        "padding:0;list-style:none;font-size:var(--font-xs)}"
        ".nu-pd-legend li{display:flex;align-items:center;gap:var(--space-1)}"
        ".nu-pd-hist{margin-top:var(--space-2)}"
        # 最近の変化
        ".nu-pd-chglist{margin:0;padding:0;list-style:none}"
        ".nu-pd-chg{display:grid;gap:2px;padding:var(--space-2) 0;border-bottom:1px solid var(--color-border)}"
        ".nu-pd-chg__type{font-weight:700}.nu-pd-chg__ba{font-variant-numeric:tabular-nums}"
        f"@media (min-width:{w}px){{.nu-pd-page{{max-width:var(--max-width)}}}}"
        # 商品の検索（compact。結果は商品単位）
        ".nu-slist{display:grid;gap:var(--space-2);margin:var(--space-2) 0 0;padding:0;list-style:none}"
        ".nu-srow{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:var(--space-1) var(--space-2);"
        "align-items:center;padding:var(--space-2) var(--space-3);border:1px solid var(--color-border);"
        "border-radius:var(--radius-md);background:var(--color-surface)}"
        ".nu-srow__main{min-width:0}.nu-srow__name{display:block;font-weight:700;overflow-wrap:anywhere}"
        ".nu-srow .nu-pdlink{grid-column:1/-1;justify-self:start;padding:0}"
        f"@media (min-width:{m}px){{.nu-srow{{grid-template-columns:minmax(0,1fr) auto auto}}"
        ".nu-srow .nu-pdlink{grid-column:auto;justify-self:end;padding:0 var(--space-2)}}"
        f"@media (min-width:{d}px){{.nu-slist{{grid-template-columns:repeat(2,minmax(0,1fr))}}}}"
    )
